import { artifactCacheId, readiness } from './core.js';

const endpoint=value=>typeof value==='string'?value:value?.address??value?.name??value?.label??null;
export function localTime(value,timeZone){if(!value)return null;try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',...(timeZone?{timeZone}:{})}).format(new Date(value));}catch{return value;}}
export function eventTime(event){const t=event.temporal??{};if(event.movement)return {departure:localTime(t.start,t.startTimezone),arrival:localTime(t.end,t.endTimezone)};return {start:localTime(t.start,t.startTimezone),end:localTime(t.end,t.endTimezone)};}
export function mapUrl(location){if(!location)return null;if(typeof location==='object'&&Number.isFinite(location.latitude)&&Number.isFinite(location.longitude))return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${location.latitude},${location.longitude}`)}`;const query=endpoint(location);return query?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`:null;}
export function navigationFor(event,now=new Date().toISOString()){const spatial=event.spatial??{};if(event.movement){const departed=event.temporal?.start&&Date.parse(now)>=Date.parse(event.temporal.start);return mapUrl(departed?spatial.destination:spatial.origin);}return mapUrl(spatial.location);}
export function activeJourney(packet){return {current:{accommodation:packet.current.accommodation??[],hire:packet.current.hire??[],parking:(packet.current.parkingKnowledge??[]).map(id=>packet.knowledge.find(k=>k.id===id)).filter(Boolean)},past:[...(packet.current.past??[])].map(id=>packet.events[id]).filter(Boolean).sort((a,b)=>Date.parse(b.temporal?.end??0)-Date.parse(a.temporal?.end??0)),now:(packet.current.now??[]).map(id=>packet.events[id]).filter(Boolean),next:packet.current.next?packet.events[packet.current.next]:null,later:(packet.current.later??[]).map(id=>packet.events[id]).filter(Boolean)};}
const participantName=(trip,id,index)=>{const item=(trip.participants??[]).find(p=>(typeof p==='string'?p:p.id)===id);return typeof item==='object'?item.name??item.title??`Ticket ${index+1}`:item??`Ticket ${index+1}`;};
export function doorEntries(packet,eventId,artifacts){const event=packet.events[eventId];return (packet.access??[]).filter(access=>access.eventId===eventId).map((access,index)=>{const candidates=(access.artifactIds??[]).map(id=>(packet.artifactManifest??[]).find(a=>a.eventId===eventId&&a.id===id)).filter(Boolean);const verified=candidates.map(a=>({manifest:a,cache:artifacts.find(c=>c.id===artifactCacheId(packet.trip.id,eventId,a.id)&&c.state==='verified'&&(!a.version||a.version===c.version)&&(!a.checksum||a.checksum===c.checksum))})).filter(x=>x.cache);const code=verified.find(x=>x.manifest.code);const source=code??verified[0]??null;return {id:access.requirementId,label:participantName(packet.trip,access.participantId,index),status:access.status,ready:Boolean(source)&&access.status!=='external_dynamic',artifact:source?.manifest??null,cache:source?.cache??null,allArtifacts:verified};});}
export function ticketSummary(packet,eventId,artifacts){const eventAccess=(packet.access??[]).filter(x=>x.eventId===eventId);const r=readiness({...packet,access:eventAccess},artifacts);return r.external? 'Requires venue app':`${r.ready}/${r.required} ready offline`;}
