import { withoutDeletedEvents } from './deleted-events.js';
import { installEventDeletion } from './event-deletion.js';
import { installTripDeletion } from './trip-deletion.js';
import { recordEvent,undoEvent,retireEventReceipts } from './event-mutations.js';
import { EVENT_VISUAL_ROLES,eventVisualLabel,eventVisualRole } from '../src/event-visual.js';
import { installExplicitSave, installTimezonePicker } from './event-editor.js';
import { validateTemporal } from '../src/temporal.js';
import { calendarMarkup as renderCalendar, dayHeading, EVENT_COLORS } from './calendar.js';
import { parkingCaptureId } from '../src/parking.js';
import { installUpdates } from './updates.js';
import QRCode from 'qrcode';
import { sessionFetch, installSignIn } from './session.js';
import { diagnosticsSnapshot, installDiagnostics, workerIdentity } from './diagnostics.js';
import JsBarcode from 'jsbarcode';
import { IndexedDbStore, PerformanceTrace, replayQueue, startLocalFirst } from './core.js';
import { InteractionController, releaseAndAdoptIfSafe } from './interaction.js';
import { activeJourney, doorEntries, eventTime, journeyTime, localTime, mapUrl, navigationFor, requestLocation, ticketSummary } from './journey.js';
import { itineraryProjection, localDateTimeValue, planningDetails, tripPlanningSummary, withPendingEvents, zonedDateTimeToIso } from './planning.js';
import { hasUsableLocalPacket, newParticipantId, normalizeParticipants, participantRemovalAllowed } from './library.js';

import { artwork, artMarkup, eventIconMarkup, resolveArtwork, systemMarkup, installArtFallback } from './artwork.js';
const fixtureMode=import.meta.env.DEV && new URLSearchParams(location.search).has('porter-fixture');
const fixtureState=new URLSearchParams(location.search).get('porter-fixture')||'ready';
const fixture=fixtureMode?await (await import('./dev/fixtures.js')).createFixtures(fixtureState):null;
const store=fixture?.store??new IndexedDbStore(), root=document.querySelector('#app'), status=document.querySelector('#status'), interactions=new InteractionController();
let activeRun, packet, viewPacket, trace, deferredPacket=null, door={eventId:null,index:0}, surface='journey', perspectiveParticipantId=null;
let calendarMode='week',calendarWeek=null,calendarTrip=null;
let lastRequestError=null,swError=null,updates=null,lastEventSaveMs=null;
const request=sessionFetch({onAuthenticationRequired:()=>{document.querySelector('#account').textContent='Sign in';}});
const headers=()=>({});
const fail=async response=>{if(response.ok)return response;const body=await response.json().catch(()=>({}));lastRequestError={status:response.status,code:body.code??'request_failed',requestId:response.headers.get('X-Request-ID')};const error=new Error(response.status===401?'Sign in to synchronize; your saved data is still available.':body.message??'Porter request failed');error.code=response.status===409?'revision_conflict':response.status===401?'authentication_failed':response.status===400?'invalid_semantic_input':response.status===404?'not_found':'backend_error';throw error;};
const productionApi={eventDeletionPreview:async id=>(await fail(await request(`/client/events/${id}/deletion`,{signal:AbortSignal.timeout(30000)}))).json(),deleteEvent:async(id,expected)=>(await fail(await request(`/client/events/${id}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected}),signal:AbortSignal.timeout(30000)}))).json(),deletionPreview:async id=>(await fail(await request(`/client/trips/${id}/deletion`,{signal:AbortSignal.timeout(30000)}))).json(),deleteTrip:async(id,expected)=>(await fail(await request(`/client/trips/${id}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected}),signal:AbortSignal.timeout(30000)}))).json(),trips:async()=>(await fail(await request('/client/trips',{headers:headers()}))).json(),packet:async(id,perspective=null,{signal}={})=>(await fail(await request(`/client/trips/${id}/packet${perspective ? `?perspective=${encodeURIComponent(perspective)}` : ''}`,{headers:headers(),signal}))).json(),artifact:async(a,{signal}={})=>{const r=await fail(await request(`/client/artifacts/${a.eventId}/${a.id}`,{headers:headers(),signal}));return {data:await r.arrayBuffer(),version:r.headers.get('X-Porter-Artifact-Version')||undefined,checksum:r.headers.get('X-Porter-Artifact-Checksum')||undefined};},mutate:async mutation=>(await fail(await request('/client/mutate',{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify(mutation),signal:AbortSignal.timeout(30000)}))).json()};
const api=fixture?.api??productionApi;
installArtFallback(document);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const participants=ids=>(ids??[]).map(id=>{const item=(viewPacket.trip.participants??[]).find(p=>(typeof p==='string'?p:p.id)===id);return typeof item==='object'?item.name??item.id:item??id;}).join(', ');
const navTabs=()=>`<nav class="tabs" aria-label="Trip views"><button id="library">Trips</button><button data-surface="journey" aria-pressed="${surface==='journey'}">Journey</button><button data-surface="itinerary" aria-pressed="${surface==='itinerary'}">Itinerary</button><button data-surface="calendar" aria-pressed="${surface==='calendar'}">Calendar</button><select id="perspective" aria-label="Participant perspective"><option value="">Everyone</option>${(packet?.trip?.participants??[]).map(p=>`<option value="${esc(typeof p==='string'?p:p.id)}" ${perspectiveParticipantId===(typeof p==='string'?p:p.id)?'selected':''}>${esc(typeof p==='string'?p:p.name)}</option>`).join('')}</select></nav>`;
const eventCard=(event,artifacts,emphasis='')=>{const nav=navigationFor(event,new Date().toISOString()),tickets=(viewPacket.access??[]).some(a=>a.eventId===event.id),time=eventTime(event),summary=tickets?ticketSummary(viewPacket,event.id,artifacts):null,icon=emphasis==='next'?'':eventIconMarkup(event);return `<article class="event ${emphasis} commitment-${esc(event.commitment??'planned')}${event.pending?' pending':''}${event.pendingConflict?' conflict':''}">${emphasis==='next'?artMarkup(resolveArtwork(event),'event-art')+artMarkup(artwork.stamp.next,'stamp'):'' }<button class="event-open${icon?' has-event-icon':''}" data-event="${esc(event.id)}">${icon}${icon?'<span class="event-copy">':''}<strong>${esc(event.title)}</strong>${event.pendingConflict?'<small>Conflict needs resolution</small>':event.pending?'<small>Pending sync</small>':''}${['optional','cancelled'].includes(event.commitment)?`<small>${esc(event.commitment)}</small>`:''}<span>${surface==='journey'?esc(journeyTime(event)):`${esc(time.departure??time.start??'Timing not set')}${time.arrival?` → ${esc(time.arrival)}`:time.end?` – ${esc(time.end)}`:''}`}</span>${event.movement?`<small>${esc(event.spatial?.origin?.name??event.spatial?.origin??'Origin')} → ${esc(event.spatial?.destination?.name??event.spatial?.destination??'Destination')}</small>`:''}${event.participants?.length?`<small>${esc(participants(event.participants))}</small>`:''}${icon?'</span>':''}</button><div class="actions">${nav?`<a href="${nav}" target="_blank" rel="noopener">Navigate</a>`:''}${tickets?`<button data-tickets="${esc(event.id)}">${esc(summary)}</button>`:''}</div></article>`;};
function currentCard(kind,item){const event=viewPacket.events[item.eventId],loc=item.location,nav=mapUrl(loc),knowledge=(item.knowledge??[]).map(k=>k.content).filter(Boolean).join(' · ');return `<article class="current-card">${artMarkup(artwork.current[kind==='Stay'?'accommodation':'hire'],'state-art')}<b>${kind}</b><strong>${esc(event?.title??kind)}</strong>${loc?`<span>${esc(typeof loc==='string'?loc:loc.name??loc.address??'')}</span>`:''}${knowledge?`<small>${esc(knowledge)}</small>`:''}${item.checkout?`<small>Ends ${esc(localTime(item.checkout,event?.temporal?.endTimezone))}</small>`:''}<div>${nav?`<a href="${nav}" target="_blank" rel="noopener">Navigate</a>`:''}<button data-event="${esc(item.eventId)}">Details</button></div></article>`;}
function journeyMarkup(artifacts,pending){const journey=activeJourney(viewPacket,{pendingMutations:pending});return `${planningHeader()}<section class="current"><h2>Current state</h2><div class="current-strip">${journey.current.accommodation.map(x=>currentCard('Stay',x)).join('')}${journey.current.hire.map(x=>currentCard('Hire',x)).join('')}${journey.current.parking.map(k=>`<article class="current-card">${artMarkup(artwork.current.parked,'state-art')}<b>Parking${k.pending?' • pending sync':''}</b><strong>${esc(k.title)}</strong><small>${esc(k.content)}</small><button data-clear-parking="${esc(k.id)}"${parkingCaptureId(k)?` data-capture-id="${esc(parkingCaptureId(k))}"`: ''}>Clear parking</button>${mapUrl(k.locations?.[0])?`<a href="${mapUrl(k.locations[0])}" target="_blank" rel="noopener">Navigate back</a>`:''}</article>`).join('')}${!journey.current.accommodation.length&&!journey.current.hire.length&&!journey.current.parking.length?'<p class="current-empty">No current state</p>':''}</div></section><section><button id="past-toggle">Past · ${journey.past.length} events</button><div id="past" hidden>${journey.past.map(e=>eventCard(e,artifacts)).join('')}</div></section><section><h2>Now</h2>${journey.now.map(e=>eventCard(e,artifacts)).join('')||'<p>Nothing is happening now.</p>'}</section><section><h2>Next</h2>${journey.next?eventCard(journey.next,artifacts,'next'):'<p>No timed next Event.</p>'}</section><section><h2>Later</h2>${journey.later.map(e=>eventCard(e,artifacts)).join('')||'<p>Nothing later yet.</p>'}</section><button class="quick" id="quick">＋ Quick actions</button>`;}
function planningHeader(){const summary=tripPlanningSummary(viewPacket),names=summary.participants.map(p=>typeof p==='object'?p.name??p.id:p).join(', '),span=summary.startDay?`${summary.startDay}${summary.endDay&&summary.endDay!==summary.startDay?` – ${summary.endDay}`:''}`:'Dates not set';return `<section class="trip-overview">${artMarkup(resolveArtwork(viewPacket.trip,{kind:'trip',slot:'hero_asset'})??(surface==='journey'?artwork.brand.hero:null),'trip-hero')}<span class="eyebrow">Field notes · ${esc(summary.lifecycle??'draft')}</span><h1>${esc(summary.title)}</h1><small>${esc(summary.lifecycle??'draft')} · ${esc(span)}</small>${names?`<small>${esc(names)}</small>`:''}</section>`;}
function itineraryMarkup(artifacts){const itinerary=itineraryProjection(viewPacket);const day=group=>`<section class="itinerary-day"><h2>${esc(dayHeading(group.day))}</h2>${group.events.map(({event,parent},i)=>`${parent&&(!i||group.events[i-1].parent?.id!==parent.id)?`<h3 class="composite">${esc(parent.title)}</h3>`:''}${eventCard(event,artifacts)}`).join('')}</section>`;return `${planningHeader()}${itinerary.days.map(day).join('')}${itinerary.unscheduled.length?`<section><h2>Unscheduled</h2>${itinerary.unscheduled.map(event=>eventCard(event,artifacts)).join('')}</section>`:''}<button class="quick" id="add-event">＋ Add event</button>`;}
function calendarMarkup(){
  if(calendarTrip!==viewPacket.trip.id){calendarTrip=viewPacket.trip.id;calendarWeek=null;calendarMode='week';}
  const result=renderCalendar(viewPacket,{mode:calendarMode,week:calendarWeek,now:fixture?.now,esc});
  calendarWeek=result.week;
  return `${planningHeader()}${result.html}<button class="quick" id="add-event">＋ Add event</button>`;
}

async function render(next,{local,trace:nextTrace}){if(await store.isTripDeleted(next.trip.id))return;if(interactions.active){deferredPacket={tripId:next.trip.id,perspectiveParticipantId:next.perspectiveParticipantId??perspectiveParticipantId,packet:next,local};return;}packet=next;perspectiveParticipantId=next.perspectiveParticipantId??null;trace=nextTrace;const pending=await store.pending(),tripPending=pending.filter(m=>m.arguments?.tripId===packet.trip.id),artifacts=await store.getArtifacts(packet.trip.id),records=await store.allMutations(),removedEvents=await store.deletedEventIds(next.trip.id);if(await store.isTripDeleted(next.trip.id))return;if(interactions.active){deferredPacket={tripId:packet.trip.id,perspectiveParticipantId,packet,local};return;}deferredHydration=null;viewPacket=withoutDeletedEvents(withPendingEvents(packet,records),removedEvents);status.textContent=tripPending.some(m=>m.state==='conflict')?'Edit conflict • resolution required':tripPending.length?'Saved locally · pending sync':local?'Local trip • syncing in background':'Sync complete';root.dataset.surface=surface;root.innerHTML=`${navTabs()}${surface==='journey'?journeyMarkup(artifacts,tripPending):surface==='itinerary'?itineraryMarkup(artifacts):calendarMarkup()}<dialog id="details"></dialog><dialog id="door"></dialog><dialog id="quick-dialog"></dialog>`;if(surface==='itinerary'){trace.markFirst('planning_open_start');trace.markFirst('itinerary_visible');}if(surface==='calendar'){trace.markFirst('planning_open_start');trace.markFirst('calendar_visible');}bind(artifacts);document.querySelector('#visual-notice').innerHTML=!navigator.onLine?systemMarkup('offline-ready'):'';}
// The app root also carries data-surface as layout metadata; only tab buttons own navigation.
function bind(artifacts){
root.querySelectorAll('[data-calendar-mode]').forEach(button=>button.onclick=()=>{calendarMode=button.dataset.calendarMode;render(packet,{local:true,trace});});
root.querySelectorAll('[data-week]').forEach(button=>button.onclick=()=>{calendarWeek=button.dataset.week;render(packet,{local:true,trace});});
document.querySelector('#library')?.addEventListener('click',openLibrary);document.querySelector('#perspective')?.addEventListener('change',event=>switchPerspective(event.target.value||null));root.querySelectorAll('.tabs > button[data-surface]').forEach(button=>button.onclick=async()=>{if(interactions.active)return;surface=button.dataset.surface;await render(packet,{local:true,trace});});document.querySelector('#past-toggle')?.addEventListener('click',()=>{const past=document.querySelector('#past');past.hidden=!past.hidden;});document.querySelectorAll('[data-event]').forEach(button=>button.onclick=()=>openDetails(button.dataset.event,artifacts));document.querySelectorAll('[data-tickets]').forEach(button=>button.onclick=()=>openDoor(button.dataset.tickets,artifacts));document.querySelector('#quick')?.addEventListener('click',openQuick);document.querySelector('#add-event')?.addEventListener('click',()=>openCreateEvent());root.querySelectorAll('[data-clear-parking]').forEach(button=>button.onclick=()=>saveParking({operation:'clearCurrentParking',arguments:{tripId:packet.trip.id,...(button.dataset.captureId?{captureId:button.dataset.captureId}:{knowledgeId:button.dataset.clearParking})}}));}
function detailsMarkup(detail,artifacts){const e=detail.event,time=eventTime(e),ticket=detail.access.length?`<button id="passes">Passes · ${esc(ticketSummary(viewPacket,e.id,artifacts))}</button>`:'';return `<button autofocus id="close">Close</button><button id="edit">Edit</button><h2>${esc(e.title)}</h2>${e.pending?'<p>Pending sync</p>':''}${e.description?`<p>${esc(e.description)}</p>`:''}<p>${esc(time.departure??time.start??'Timing not set')}${time.arrival?` → ${esc(time.arrival)}`:time.end?` – ${esc(time.end)}`:''}</p>${e.spatial?.location?`<p>${esc(e.spatial.location.name??e.spatial.location.address??e.spatial.location)}</p>`:''}${e.movement?`<p>${esc(e.spatial?.origin?.name??e.spatial?.origin??'')} → ${esc(e.spatial?.destination?.name??e.spatial?.destination??'')}</p>`:''}${e.participants?.length?`<p>Participants: ${esc(participants(e.participants))}</p>`:''}<p>Commitment: ${esc(e.commitment??'planned')}</p>${detail.knowledge.map(k=>`<p><strong>${esc(k.title)}:</strong> ${esc(k.content)}</p>`).join('')}${e.provenance?.length?`<p>Source: ${esc(e.provenance.map(x=>typeof x==='string'?x:x.label??x.url??'').filter(Boolean).join(', '))}</p>`:''}${ticket}`;}
function openDetails(id,artifacts){const owner=interactions.begin('details'),detail=planningDetails(viewPacket,id),d=document.querySelector('#details');if(!detail)return;trace.markFirst('event_details_visible');d.innerHTML=detailsMarkup(detail,artifacts);d.showModal();d.querySelector('#close').onclick=()=>d.close();d.querySelector('#edit').onclick=()=>openEditEvent(detail.event,d,owner);d.querySelector('#passes')?.addEventListener('click',()=>{const doorOwner=interactions.begin('door');d.close();openDoor(id,artifacts,doorOwner);});onDialogClose(d,owner);}
const formValue=(form,name)=>form.elements[name].value.trim();
function eventForm(event={}){const t=event.temporal??{},s=event.spatial??{};return `<form id="event-form"><label>Title<input name="title" required value="${esc(event.title??'')}"></label><label>Description<textarea name="description">${esc(event.description??'')}</textarea></label><label>Start<input name="start" type="datetime-local" min="1900-01-01T00:00" max="2100-12-31T23:59" value="${esc(localDateTimeValue(t.start,t.startTimezone))}"></label><div class="timezone-picker"><label><span data-zone-label>Timezone</span><input type="search" data-zone-search="startTimezone" aria-label="Search timezone cities" placeholder="Search cities" autocomplete="off"></label><select name="startTimezone" aria-label="Timezone"></select><small data-zone-mode></small></div><label>End<input name="end" type="datetime-local" min="1900-01-01T00:00" max="2100-12-31T23:59" value="${esc(localDateTimeValue(t.end,t.endTimezone))}"></label><div class="timezone-picker" data-end-zone hidden><label>Arrival timezone<input type="search" data-zone-search="endTimezone" aria-label="Search arrival timezone cities" placeholder="Search cities" autocomplete="off"></label><select name="endTimezone" aria-label="Arrival timezone"></select></div><label><input name="movement" type="checkbox" ${event.movement?'checked':''}> Movement</label><label>Location<input name="location" value="${esc(s.location?.address??s.location?.name??'')}"></label><label>Origin<input name="origin" value="${esc(s.origin?.address??s.origin?.name??s.origin??'')}"></label><label>Destination<input name="destination" value="${esc(s.destination?.address??s.destination?.name??s.destination??'')}"></label><label>Participants (IDs, comma separated)<input name="participants" value="${esc((event.participants??[]).join(', '))}"></label><label>Commitment<select name="commitment">${['optional','planned','confirmed','completed','cancelled'].map(x=>`<option ${event.commitment===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Visual illustration<select name="visualRole">${EVENT_VISUAL_ROLES.map(role=>`<option value="${role}" ${eventVisualRole(event)===role?'selected':''}>${eventVisualLabel(role)}</option>`).join('')}</select></label><label>Calendar color<select name="calendarColor"><option value="">Default</option>${EVENT_COLORS.map(c=>`<option value="${c.id}" ${event.visual?.color===c.id?'selected':''}>${c.label}</option>`).join('')}</select></label><button type="button" data-save-event>Save</button></form>`;}
function formEvent(form,existing={}){if(!formValue(form,'title'))throw new TypeError('Event title is required');const movement=form.elements.movement.checked,location=formValue(form,'location'),origin=formValue(form,'origin'),destination=formValue(form,'destination'),startZone=formValue(form,'startTimezone'),endZone=movement?formValue(form,'endTimezone'):startZone,old=existing.temporal??{};const temporal={};for(const name of ['start','end'])if(form.elements[name].validity.badInput)throw new TypeError('Complete or clear the '+name+' date and time.');if(formValue(form,'start'))temporal.start=old.start&&formValue(form,'start')===localDateTimeValue(old.start,startZone)&&(!old.startTimezone||old.startTimezone===startZone)?old.start:zonedDateTimeToIso(formValue(form,'start'),startZone);else if(old.start&&!startZone)temporal.start=old.start;if(formValue(form,'end'))temporal.end=old.end&&formValue(form,'end')===localDateTimeValue(old.end,endZone)&&(!old.endTimezone||old.endTimezone===endZone)?old.end:zonedDateTimeToIso(formValue(form,'end'),endZone);else if(old.end&&!endZone)temporal.end=old.end;if(startZone)temporal.startTimezone=startZone;else if(old.startTimezone)temporal.startTimezone=old.startTimezone;if(endZone)temporal.endTimezone=endZone;else if(old.endTimezone)temporal.endTimezone=old.endTimezone;validateTemporal(temporal);const spatial=movement?{...(origin?{origin:{address:origin}}:{}),...(destination?{destination:{address:destination}}:{})}:{...(location?{location:{address:location}}:{})};return {title:formValue(form,'title'),description:formValue(form,'description')||null,temporal,spatial,movement,participants:formValue(form,'participants').split(',').map(x=>x.trim()).filter(Boolean),visual:{...(existing.visual??{}),visual_role:formValue(form,'visualRole'),color:formValue(form,'calendarColor')||null},commitment:formValue(form,'commitment'),accommodation:Boolean(existing.accommodation),hire:Boolean(existing.hire)};}
function bindEventEditor(d,event,save){
  const form=d.querySelector('#event-form');
  installTimezonePicker(form,viewPacket,event);
  const message=d.querySelector('#edit-message');message.setAttribute('role','alert');
  form.addEventListener('invalid',()=>{message.textContent='Check the highlighted field. Enter complete dates and times between 1900 and 2100.';},true);
  installExplicitSave(form,async()=>{message.textContent='';try{const input=formEvent(form,event);trace.mark('event_save_start');await save(input);trace.mark('edit_saved_local');trace.measure('event_local_save','event_save_start','edit_saved_local');lastEventSaveMs=trace.measures.event_local_save;d.close();}catch(error){message.textContent=error.message;}});
  d.querySelector('#close').onclick=()=>d.close();
}
function openEditEvent(event,d,owner){d.innerHTML=`<button type="button" id="close">Close</button><h2>Edit Event</h2>${eventForm(event)}<p id="edit-message"></p>`;trace.markFirst('edit_open');bindEventEditor(d,event,patch=>submitMutation({operation:'updateEvent',arguments:{tripId:packet.trip.id,eventId:event.id,patch,expectedRevision:event.revision}},event));installEventDeletion({dialog:d,event,tripId:packet.trip.id,api,store,esc,onDeleted:async result=>{launchGeneration++;deferredPacket=null;deferredHydration=null;clearTimeout(undoTimer);confirmation.hidden=true;interactions.release(owner);d.close();packet=withoutDeletedEvents(packet,result.eventIds);await render(packet,{local:true,trace});status.textContent=result.cleanupPending?'Event deleted · some stored files need server cleanup':'Event deleted';deletionChannel?.postMessage({tripId:packet.trip.id,eventIds:result.eventIds});void launch(packet.trip.id,perspectiveParticipantId,false);}});}
function openCreateEvent(owner=interactions.begin('edit')){const d=document.querySelector('#quick-dialog');d.innerHTML=`<button type="button" id="close">Close</button><h2>Add Event</h2>${eventForm({commitment:'planned'})}<p id="edit-message"></p>`;d.showModal();trace.markFirst('edit_open');bindEventEditor(d,{},event=>submitMutation({operation:'createEvent',arguments:{tripId:packet.trip.id,event}}));onDialogClose(d,owner);}

async function saveParking(mutation){
  await store.enqueue(mutation);
  if(interactions.active)deferredPacket={tripId:packet.trip.id,perspectiveParticipantId,packet,local:true};
  else {await render(packet,{local:true,trace});if(navigator.onLine)launch(packet.trip.id,perspectiveParticipantId);}
}
async function adoptMutation(next,local){
  if(interactions.active)deferredPacket={tripId:next.trip.id,perspectiveParticipantId,packet:next,local};
  else await render(next,{local,trace});
}
let eventSync=null,eventSyncAgain=false;
function syncEvents(){
  if(!navigator.onLine)return;
  if(eventSync){eventSyncAgain=true;return eventSync;}
  eventSync=(async()=>{do{eventSyncAgain=false;const tripId=packet?.trip.id;await replayQueue(store,api);if(packet?.trip.id===tripId&&!['preparing','library'].includes(root.dataset.surface))await launch(tripId,perspectiveParticipantId,false);}while(eventSyncAgain);})().catch(()=>{status.textContent='Saved locally · sync failed; tap Sync to retry';}).finally(()=>eventSync=null);
  return eventSync;
}
let undoTimer;
const confirmation=document.createElement('aside');confirmation.id='event-confirmation';confirmation.hidden=true;document.body.append(confirmation);
function savedNotice(record){
  clearTimeout(undoTimer);confirmation.hidden=false;confirmation.innerHTML='<span role="status">Saved</span> · <button type="button">Undo</button>';
  confirmation.querySelector('button').onclick=async()=>{
    if(interactions.active)return;
    const button=confirmation.querySelector('button');button.disabled=true;
    try{await undoEvent(store,record.id);await adoptMutation(packet,true);confirmation.innerHTML='<span role="status">Undone</span>';syncEvents();}
    catch(error){confirmation.textContent=error.message;}
  };
  undoTimer=setTimeout(()=>{confirmation.hidden=true;},Math.max(0,record.undoUntil-Date.now()));
}
async function submitMutation(mutation,before=null){
  if(['createEvent','updateEvent'].includes(mutation.operation)){
    const record=await recordEvent(store,mutation,before);await adoptMutation(packet,true);savedNotice(record);return;
  }
  return submitOtherMutation(mutation);
}
async function submitOtherMutation(mutation){let acknowledged=false;try{if(navigator.onLine){await api.mutate(mutation);acknowledged=true;const fresh=await api.packet(packet.trip.id,perspectiveParticipantId);await store.putPacket(packet.trip.id,{packet:fresh,meta:{revision:fresh.revision,generatedAt:fresh.generatedAt,lastSync:new Date().toISOString(),usable:true}},perspectiveParticipantId);await adoptMutation(fresh,false);return;}}catch(error){if(acknowledged){status.textContent='Saved · refresh unavailable; sync again when connected';return;}if(error.code==='invalid_semantic_input')throw error;if(error.code==='revision_conflict'){await store.enqueue({...mutation,state:'conflict',error:error.message});status.textContent='Edit conflict • resolution required';await adoptMutation(packet,true);return;}}await store.enqueue(mutation);status.textContent='Saved locally • pending sync';await adoptMutation(packet,true);}
async function drawCode(entry){const host=document.querySelector('#code');if(!entry.artifact?.code)return;const {format,value}=entry.artifact.code;if(format==='qr'){const canvas=document.createElement('canvas');await QRCode.toCanvas(canvas,value,{width:300,margin:1});host.replaceChildren(canvas);}else{const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');JsBarcode(svg,value,{format:format==='code128'?'CODE128':format.toUpperCase(),displayValue:true,width:2,height:120});host.replaceChildren(svg);}}
async function openDoor(eventId,artifacts,owner=interactions.begin('door')){door={eventId,index:0};trace.markFirst('door_mode_open_start');const d=document.querySelector('#door');d.showModal();const show=async()=>{const entries=doorEntries(viewPacket,eventId,artifacts),entry=entries[door.index];trace.markFirst('ticket_artifact_lookup_complete');const external=entry.appUrl?`<a href="${esc(entry.appUrl)}" target="_blank" rel="noopener">Open venue app</a>`:entry.sourceUrl?`<a href="${esc(entry.sourceUrl)}" target="_blank" rel="noopener">Open ticket source</a>`:'';d.innerHTML=`<button id="close">Close</button><h1>${esc(viewPacket.events[eventId].title)}</h1><p>${door.index+1} of ${entries.length} · ${esc(entry.label)}</p><div id="code" class="ticket">${entry.status==='external_dynamic'?'Requires venue app':entry.ready?'Loading ticket…' :systemMarkup('missing-artifact')}</div><div class="door-actions"><button id="prev" ${door.index?'':'disabled'}>Previous</button><button id="next" ${door.index<entries.length-1?'':'disabled'}>Next</button>${entry.cache?'<button id="original">Open original</button>':''}${external}</div>`;if(entry.artifact?.code){await drawCode(entry);trace.markFirst('ticket_visible');trace.markFirst('door_mode_interactive');}else if(entry.cache){d.querySelector('#code').textContent='Cached original ticket ready';trace.markFirst('ticket_visible');trace.markFirst('door_mode_interactive');}d.querySelector('#prev').onclick=()=>{door.index--;show();};d.querySelector('#next').onclick=()=>{door.index++;show();};d.querySelector('#original')?.addEventListener('click',()=>openOriginal(entry));d.querySelector('#close').onclick=()=>d.close();};await show();onDialogClose(d,owner);}
function openOriginal(entry){window.open(URL.createObjectURL(new Blob([entry.cache.data],{type:entry.cache.mediaType})),'_blank','noopener');}
function openQuick(){const owner=interactions.begin('quick'),d=document.querySelector('#quick-dialog');d.innerHTML=`<button id="close">Close</button><h2>Quick actions</h2><button id="add-event">Add event</button><button id="location">Save this location</button><button id="parking">I parked here</button><p id="quick-message"></p>`;d.showModal();d.querySelector('#close').onclick=()=>d.close();d.querySelector('#add-event').onclick=()=>{const editOwner=interactions.begin('edit');d.close();openCreateEvent(editOwner);};d.querySelector('#location').onclick=()=>capture('location');d.querySelector('#parking').onclick=()=>capture('parking');onDialogClose(d,owner);}
async function capture(kind){try{const point=await requestLocation(navigator.geolocation);await (kind==='parking'?saveParking:submitMutation)({operation:kind==='parking'?'setCurrentParking':'createKnowledge',arguments:{tripId:packet.trip.id,knowledge:{title:kind==='parking'?'Current parking':'Saved location',content:kind==='parking'?'Saved parking location':'Saved current location',locations:[point],sources:kind==='parking'?[{type:'porter-parking-capture',id:crypto.randomUUID()}]:[],tags:kind==='parking'?['parking','current']:[]}}});document.querySelector('#quick-dialog')?.close();}catch(error){document.querySelector('#quick-message').textContent=error.message;}}
const participantRows=(people=[])=>people.map(person=>`<label>${esc(person.name??person)}<input data-participant-id="${esc(person.id??newParticipantId())}" value="${esc(person.name??person)}"></label>`).join('');
const readParticipants=dialog=>normalizeParticipants([...dialog.querySelectorAll('[data-participant-id]')].map(input=>({id:input.dataset.participantId,name:input.value})));
let libraryGeneration=0;
async function openLibrary(){const generation=++libraryGeneration;if(interactions.active){status.textContent='Finish the current interaction before switching Trips.';return;}launchGeneration++;root.dataset.surface='library';trace?.markFirst('trip_library_visible');const draw=async()=>{const rows=await store.listTripIndex(),lifecycle=['active','upcoming','draft','archived'],rowMarkup=row=>`<article class="event"><button data-trip="${esc(row.id)}"><strong>${esc(row.title)}</strong>${row.id===packet?.trip?.id?'<small>Currently open on this device</small>':''}<small>${esc(row.lifecycle??'draft')} · ${(row.participants??[]).map(p=>esc(p.name??p)).join(', ')}</small><small>${row.usable?'Available offline':'Needs sync'}${row.lastSync?` · synced ${esc(row.lastSync)}`:''}</small></button><button data-trip-edit="${esc(row.id)}">Edit</button></article>`;if(generation!==libraryGeneration||root.dataset.surface!=='library'||interactions.active)return;root.innerHTML=`<section><h1>Trips</h1>${rows.length?lifecycle.map(state=>{const group=rows.filter(row=>(row.lifecycle??'draft')===state);return group.length?`<section class="trip-library-group"><h2>${esc(state[0].toUpperCase()+state.slice(1))}</h2>${group.map(rowMarkup).join('')}</section>`:'';}).join(''):systemMarkup('no-active-trip')}<button id="create-trip">Create Trip</button><p id="library-message"></p></section><dialog id="library-dialog"></dialog>`;root.querySelectorAll('[data-trip]').forEach(button=>button.onclick=()=>selectTrip(button.dataset.trip));root.querySelectorAll('[data-trip-edit]').forEach(button=>button.onclick=()=>openTripEdit(button.dataset.trip));root.querySelector('#create-trip').onclick=openCreateTrip;};await draw();if(navigator.onLine){api.trips().then(async trips=>{for(const trip of trips)await store.upsertTripIndex(trip);if(!interactions.active&&generation===libraryGeneration)await draw();}).catch(()=>{const message=root.querySelector('#library-message');if(message)message.textContent='Online Trip refresh unavailable; showing local library. Sign in if needed.';});}}
async function selectTrip(tripId){if(interactions.active)return;libraryGeneration++;const cached=await store.getPacket(tripId,null);if(!navigator.onLine&&!hasUsableLocalPacket(cached)){status.textContent='This Trip needs an online sync before it can open offline.';return;}if(hasUsableLocalPacket(cached)){deferredPacket=null;perspectiveParticipantId=null;await store.setActiveTrip(tripId,null);}trace?.markFirst('trip_switch_start');await launch(tripId,null);}
async function switchPerspective(next){if(interactions.active){status.textContent='Finish the current interaction before changing perspective.';return;}const cached=await store.getPacket(packet.trip.id,next);if(!hasUsableLocalPacket(cached)&&!navigator.onLine){status.textContent='This perspective needs an online sync first.';return;}if(hasUsableLocalPacket(cached)){deferredPacket=null;perspectiveParticipantId=next;await store.setActiveTrip(packet.trip.id,next);}trace.markFirst('perspective_switch_start');await launch(packet.trip.id,next);trace.markFirst('perspective_packet_visible');}
function openCreateTrip(){const owner=interactions.begin('trip-edit'),d=document.querySelector('#library-dialog');d.innerHTML=`<button id="close">Close</button><h2>Create Trip</h2><form id="trip-form"><label>Title<input name="title" required></label><label>Lifecycle<select name="lifecycle"><option selected>draft</option><option>upcoming</option><option>active</option></select></label><div id="trip-participants"></div><button type="button" id="add-person">Add participant</button><button>Create</button></form><p id="trip-message"></p>`;d.showModal();d.querySelector('#close').onclick=()=>d.close();d.querySelector('#add-person').onclick=()=>{d.querySelector('#trip-participants').insertAdjacentHTML('beforeend',participantRows([{id:newParticipantId(),name:''}]));};d.querySelector('#trip-form').onsubmit=async event=>{event.preventDefault();if(!navigator.onLine){d.querySelector('#trip-message').textContent='Trip creation needs a connection.';return;}try{const created=await api.mutate({operation:'createTrip',arguments:{trip:{title:event.currentTarget.title.value.trim(),lifecycle:event.currentTarget.lifecycle.value,participants:readParticipants(d)}}});const fresh=await api.packet(created.id);await store.putPacket(created.id,{packet:fresh,meta:{revision:fresh.revision,generatedAt:fresh.generatedAt,lastSync:new Date().toISOString(),usable:true}});d.close();await selectTrip(created.id);}catch(error){d.querySelector('#trip-message').textContent=error.message;}};onDialogClose(d,owner);}
async function openTripEdit(tripId){if(interactions.active)return;const owner=interactions.begin('trip-edit');const cached=await store.getPacket(tripId,null),trip=cached?.packet?.trip??(await store.listTripIndex()).find(row=>row.id===tripId);if(!trip){interactions.release(owner);return;}const d=document.querySelector('#library-dialog');d.innerHTML=`<button id="close">Close</button><h2>Edit Trip</h2><form id="trip-form"><label>Title<input name="title" required value="${esc(trip.title)}"></label><label>Lifecycle<select name="lifecycle">${['draft','upcoming','active','archived'].map(value=>`<option ${trip.lifecycle===value?'selected':''}>${value}</option>`).join('')}</select></label><div id="trip-participants">${participantRows(trip.participants??[])}</div><button type="button" id="add-person">Add participant</button><button>Save</button></form><p id="trip-message"></p>`;d.showModal();d.querySelector('#close').onclick=()=>d.close();d.querySelector('#add-person').onclick=()=>d.querySelector('#trip-participants').insertAdjacentHTML('beforeend',participantRows([{id:newParticipantId(),name:''}]));d.querySelector('#trip-form').onsubmit=async event=>{event.preventDefault();const people=readParticipants(d);for(const person of trip.participants??[])if(!people.some(p=>p.id===person.id)&&cached&&!participantRemovalAllowed(cached.packet,person.id)){d.querySelector('#trip-message').textContent=`${person.name} is referenced by Events and cannot be removed yet.`;return;}try{const changed=await api.mutate({operation:'updateTrip',arguments:{tripId,patch:{title:event.currentTarget.title.value.trim(),lifecycle:event.currentTarget.lifecycle.value,participants:people},expectedRevision:trip.revision}});await store.upsertTripIndex(changed,{usable:Boolean(cached?.meta?.usable)});d.close();if(packet?.trip?.id===tripId)await launch(tripId,perspectiveParticipantId);else await openLibrary();}catch(error){d.querySelector('#trip-message').textContent=error.code==='revision_conflict'?'Trip edit conflict • resolution required':error.message;}};installTripDeletion({dialog:d,trip,cached:cached?.packet,api,store,esc,onDeleted:async(id,result)=>{deferredPacket=null;deferredHydration=null;launchGeneration++;interactions.release(owner);d.close();await leaveDeletedTrip(id);status.textContent=result.cleanupPending?'Trip deleted · some stored files need server cleanup':'Trip deleted';deletionChannel?.postMessage({tripId:id});}});onDialogClose(d,owner);}
// A queued close event can belong to Quick Actions before the same dialog is
// reopened as an editor. Do not release the new owner until it actually closes.
function onDialogClose(dialog,owner){const close=()=>{if(dialog.open)return;dialog.removeEventListener('close',close);safe(owner);};dialog.addEventListener('close',close);}
async function safe(owner){if(!interactions.owns(owner))return;deferredPacket=await releaseAndAdoptIfSafe(interactions,owner,deferredPacket,next=>{if(next.tripId===(hydratingTrip??packet?.trip?.id))return render(next.packet,{local:next.local??false,trace});});if(!interactions.active){if(packet?.trip?.id&&await store.isTripDeleted(packet.trip.id)){if(!interactions.active)await leaveDeletedTrip(packet.trip.id);return;}if(deferredHydration){const h=deferredHydration;hydrationState(h.phase,h.trace,h.error);}await updates?.safe();if(navigator.onLine&&(await store.pending()).length)syncEvents();}}
function hydrationState(phase,nextTrace,error){
  trace=nextTrace;hydratingTrip=trace.context.tripId;hydratingPerspective=trace.context.perspectiveParticipantId;if(interactions.active){deferredHydration={phase,trace:nextTrace,error};status.textContent=phase==='failed'?'Trip preparation failed':phase;return;}deferredHydration=null;root.dataset.surface='preparing';
  root.innerHTML=`<section class="preparing-trip" role="status"><h1>${phase==='failed'?'Trip could not be prepared':'Preparing trip…'}</h1><p>${phase==='failed'?esc(error?.message??'Connect and try again.'):esc(phase)}</p>${phase==='failed'?'<button id="retry-trip">Retry</button><button id="back-trips">Trips</button>':''}</section>`;
  root.querySelector('#retry-trip')?.addEventListener('click',()=>launch(hydratingTrip,hydratingPerspective));
  root.querySelector('#back-trips')?.addEventListener('click',openLibrary);
}
let hydratingTrip=null,hydratingPerspective=null,deferredHydration=null;
let launchGeneration=0;
async function launch(tripId=location.hash.slice(1)||null,perspective=undefined,replay=true){
  tripId=tripId??await store.getActiveTrip();if(tripId&&await store.isTripDeleted(tripId)){await leaveDeletedTrip(tripId);return;}
  deferredPacket=null;deferredHydration=null;const generation=++launchGeneration,isCurrent=()=>generation===launchGeneration;
  hydratingTrip=tripId;hydratingPerspective=perspective;
  const run=await startLocalFirst({store,tripId,perspectiveParticipantId:perspective,api,isCurrent,
    onHydration:(...args)=>{if(isCurrent())hydrationState(...args);},
    render:(...args)=>{if(isCurrent())return render(...args);},canAdopt:()=>!interactions.active,
    onDeferred:next=>{if(!isCurrent())return;deferredPacket={tripId:next.trip.id,perspectiveParticipantId:next.perspectiveParticipantId??null,packet:next};status.textContent='Update ready when you finish';},
    trace:new PerformanceTrace({revision:__PORTER_REVISION__,eventLocalSaveMs:lastEventSaveMs,online:navigator.onLine,pwa:matchMedia('(display-mode:standalone)').matches})});
  if(!isCurrent())return;activeRun=run;
  if(!run.tripId){await openLibrary();return;}
  if(run.local?.meta?.usable){perspectiveParticipantId=run.perspectiveParticipantId;if(location.hash!=='#'+run.tripId)history.replaceState(null,'','#'+run.tripId);}
  const outcome=await run.sync;if(!isCurrent())return;
  if(!outcome.ok){if(outcome.error.code==='not_found'){await store.removeTrip(run.tripId);if(!interactions.active)await leaveDeletedTrip(run.tripId);return;}status.textContent=run.local?.meta?.usable?'Sync failed · local data retained':'Trip preparation failed · Retry';document.querySelector('#visual-notice').innerHTML=packet?systemMarkup(navigator.onLine?'sync-failed':'offline-ready'):'';return;}
  perspectiveParticipantId=run.perspectiveParticipantId;if(location.hash!=='#'+run.tripId)history.replaceState(null,'','#'+run.tripId);await retireEventReceipts(store,outcome.packet);
  if(replay&&(await store.pending()).length)syncEvents();
}
async function leaveDeletedTrip(id){launchGeneration++;libraryGeneration++;deferredPacket=null;deferredHydration=null;hydratingTrip=null;confirmation.hidden=true;clearTimeout(undoTimer);if(packet?.trip?.id===id){packet=null;viewPacket=null;activeRun=null;perspectiveParticipantId=null;}if(location.hash==='#'+id)history.replaceState(null,'',location.pathname+location.search);await openLibrary();}
const deletionChannel=typeof BroadcastChannel==='function'?new BroadcastChannel('porter-trip-removal'):null;
deletionChannel?.addEventListener('message',async event=>{const id=event.data?.tripId;if(event.data?.eventIds&&packet?.trip.id===id){await render(packet,{local:true,trace});return;}if(!id||!await store.isTripDeleted(id))return;if(!interactions.active&&(packet?.trip.id===id||root.dataset.surface==='library'))await leaveDeletedTrip(id);});
if(fixtureMode){
  const controls=document.createElement('div');controls.className='fixture-controls';
  controls.innerHTML='<strong>DEVELOPMENT FIXTURE · no production data</strong><label>State <select id="fixture-state">'+['ready','partial','missing','dynamic','pending','conflict','failed','syncing','empty'].map(s=>'<option '+(s===fixtureState?'selected':'')+'>'+s+'</option>').join('')+'</select></label><button id="fixture-library">Library</button>';
  document.body.prepend(controls);
  controls.querySelector('select').onchange=e=>location.search='?porter-fixture='+e.target.value;
  controls.querySelector('button').onclick=openLibrary;

}
if(!fixtureMode)installSignIn({button:document.querySelector('#account'),interactions,onClose:safe,onSignedIn:()=>launch()});
if(new URLSearchParams(location.search).get('porter-diagnostics')==='1')installDiagnostics(async()=>diagnosticsSnapshot({store,packet,activeRun,trace,revision:__PORTER_REVISION__,online:navigator.onLine,sw:await workerIdentity(),swError,lastError:lastRequestError,update:updates?.snapshot()}));
addEventListener('online',()=>{if(!interactions.active)launch();});
launch();document.querySelector('#refresh').onclick=()=>{if(!interactions.active)launch();};
if(!import.meta.env.DEV&&'serviceWorker'in navigator)updates=installUpdates({interactions,revision:__PORTER_REVISION__,onError:error=>{swError=error;}});
