import { IndexedDbStore, PerformanceTrace, readiness, startLocalFirst } from './core.js';

const store=new IndexedDbStore();const root=document.querySelector('#app');const status=document.querySelector('#status');let activeRun;
const headers=()=>({Authorization:`Bearer ${localStorage.porterToken??''}`});
const fail=async response=>{if(response.ok)return response;const error=new Error((await response.json().catch(()=>({}))).message??'Porter request failed');error.code=response.status===409?'revision_conflict':response.status===401?'authentication_failed':'backend_error';throw error;};
const api={
  packet:async id=>(await fail(await fetch(`/client/trips/${id}/packet`,{headers:headers()}))).json(),
  artifact:async artifact=>{const response=await fail(await fetch(`/client/artifacts/${artifact.eventId}/${artifact.id}`,{headers:headers()}));return {data:await response.arrayBuffer(),version:response.headers.get('X-Porter-Artifact-Version')||undefined,checksum:response.headers.get('X-Porter-Artifact-Checksum')||undefined};},
  mutate:async mutation=>(await fail(await fetch('/client/mutate',{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify(mutation)}))).json()
};
const display=value=>JSON.stringify(value,null,2);
async function render(packet,{local,trace}){const next=packet.events[packet.current.next];const artifacts=await store.getArtifacts();const cacheReadiness=readiness(packet,artifacts);const pending=await store.pending();status.textContent=local?'Local packet ready • syncing in background':'Packet synchronized';root.innerHTML=`<h1>${packet.trip.title}</h1><section><b>Now</b> ${(packet.current.now??[]).map(id=>packet.events[id]?.title).join(', ')||'—'}</section><section><b>Next</b> ${next?.title||'—'}</section><section><b>Later</b> ${(packet.current.later??[]).length}</section><section id="ready">${cacheReadiness.ready}/${cacheReadiness.required} ready offline${cacheReadiness.external?` • ${cacheReadiness.external} external/dynamic`:''}</section><details><summary>Developer diagnostics</summary><pre>${display({tripId:packet.trip.id,packetRevision:packet.revision,generatedAt:packet.generatedAt,lastSuccessfulSync:local?undefined:new Date().toISOString(),localPacket:local?'known-good':'fresh',pendingMutations:pending.length,conflicts:pending.filter(item=>item.state==='conflict').length,artifactManifestCount:(packet.artifactManifest??[]).length,requiredArtifacts:{present:cacheReadiness.ready,missing:cacheReadiness.missing},perspective:packet.perspective??null,timings:trace.json(),warnings:packet.warnings??[]})}</pre><button id="copy-trace">Copy performance trace</button> <button id="verify-cache">Verify artifact cache</button> <button id="clear-packet">Clear local packet</button></details><button id="detail">Inspect next Event</button>`;document.querySelector('#detail')?.addEventListener('click',()=>alert(display(next)));document.querySelector('#copy-trace')?.addEventListener('click',()=>navigator.clipboard?.writeText(display(trace.json())));document.querySelector('#verify-cache')?.addEventListener('click',()=>alert(display(readiness(packet,artifacts))));document.querySelector('#clear-packet')?.addEventListener('click',async()=>{if(confirm('Clear only this local TripPacket?')){await store.putPacket(packet.trip.id,{packet:null,meta:{usable:false}});location.reload();}});}
const tripId=location.hash.slice(1);
async function launch(){if(!tripId){root.textContent='No local Trip selected yet.';return;}activeRun=await startLocalFirst({store,tripId,api,render,trace:new PerformanceTrace({coldStart:!sessionStorage.porterStarted,online:navigator.onLine,packetExisted:false,pwa:matchMedia('(display-mode:standalone)').matches})});sessionStorage.porterStarted='1';activeRun.sync.then(()=>{if(status.textContent.includes('syncing'))status.textContent='Sync complete';});}
launch();document.querySelector('#refresh').onclick=()=>launch();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
