import test from 'node:test';
import assert from 'node:assert/strict';
import { MemoryStore, artifactCacheId, checksum, readiness, replayQueue, startLocalFirst, syncPacket } from '../client/core.js';
import { dispatchClientMutation, handleClientMutation } from '../client-api/server.mjs';
const bytes=text=>new TextEncoder().encode(text).buffer;
async function packetFor(artifacts=[]){return {packetVersion:1,revision:1,generatedAt:'2026-01-01T00:00:00Z',trip:{id:'t',title:'Trip'},events:{e:{title:'Next'}},current:{now:[],next:'e',later:[]},artifactManifest:artifacts,access:artifacts.map(artifact=>({status:'expected',eventId:artifact.eventId,artifactIds:[artifact.id]}))};}
async function required(id,body='ticket'){return {id,eventId:'e',offlineRequired:true,version:'v1',checksum:await checksum(bytes(body)),mediaType:'application/pdf'};}
test('local packet renders before an unresolved network sync',async()=>{const packet=await packetFor();const store=new MemoryStore();await store.putPacket('t',{packet,meta:{usable:true}});let render=0;let resolve;const run=await startLocalFirst({store,tripId:'t',api:{packet:()=>new Promise(done=>resolve=done),artifact:async()=>({})},render:async()=>render++});assert.equal(render,1);assert.ok(run.trace.marks.background_sync_start<=(run.trace.marks.background_sync_complete??Infinity));resolve(packet);await run.sync;});
test('successful sync safely adopts a newer packet after rendering local data',async()=>{const old=await packetFor(),newer={...await packetFor(),revision:2,trip:{id:'t',title:'Updated Trip'}};const store=new MemoryStore();await store.putPacket('t',{packet:old,meta:{usable:true}});const rendered=[];const run=await startLocalFirst({store,tripId:'t',api:{packet:async()=>newer,artifact:async()=>null},render:async packet=>rendered.push(packet.trip.title)});await run.sync;assert.deepEqual(rendered,['Trip','Updated Trip']);});
test('successful sync defers adoption while Door Mode is open',async()=>{const old=await packetFor(),newer={...await packetFor(),revision:2};const store=new MemoryStore();await store.putPacket('t',{packet:old,meta:{usable:true}});const deferred=[];const run=await startLocalFirst({store,tripId:'t',api:{packet:async()=>newer,artifact:async()=>null},render:async()=>{},canAdopt:()=>false,onDeferred:packet=>deferred.push(packet)});await run.sync;assert.equal(deferred[0].revision,2);});
test('failed background sync returns structured failure and retains the local packet',async()=>{const packet=await packetFor();const store=new MemoryStore();await store.putPacket('t',{packet,meta:{usable:true}});let renders=0;const run=await startLocalFirst({store,tripId:'t',api:{packet:async()=>{throw new Error('network unavailable');},artifact:async()=>null},render:async()=>renders++});const outcome=await run.sync;assert.deepEqual(outcome,{ok:false,error:{code:'sync_failed',name:'Error',message:'network unavailable'},localRetained:true});assert.equal(renders,1);assert.deepEqual((await store.getPacket('t')).packet,packet);});
test('cold launch resolves the locally selected Trip without a hash or network',async()=>{const packet=await packetFor();const store=new MemoryStore();await store.putPacket('t',{packet,meta:{usable:true}});await store.setActiveTrip('t');let renders=0;const run=await startLocalFirst({store,api:{packet:async()=>{throw new Error('offline');},artifact:async()=>null},render:async()=>renders++});assert.equal(run.tripId,'t');assert.equal(renders,1);await run.sync;});
test('malformed candidate and required artifact failure preserve the known-good packet and cache',async()=>{const old=await packetFor();const artifact=await required('a');const candidate=await packetFor([artifact]);const store=new MemoryStore();await store.putPacket('t',{packet:old,meta:{usable:true}});await store.putArtifact({id:'old',state:'verified',version:'old',checksum:'old'});assert.equal((await syncPacket({store,tripId:'t',api:{packet:async()=>({bad:true})},fetchArtifact:async()=>null})).trip.id,'t');await syncPacket({store,tripId:'t',api:{packet:async()=>candidate},fetchArtifact:async()=>{throw new Error('offline');}});assert.deepEqual((await store.getArtifacts()).map(item=>item.id),['old']);assert.equal((await store.getPacket('t')).packet.revision,1);});
test('staged required artifacts do not leak when a later download fails; optional artifacts do not block',async()=>{const one=await required('a','one'),two=await required('b','two');const packet=await packetFor([one,two,{id:'optional',eventId:'e',offlineRequired:false,version:'v1',mediaType:'text/plain'}]);const store=new MemoryStore();await assert.rejects(syncPacket({store,tripId:'t',api:{packet:async()=>packet},fetchArtifact:async artifact=>artifact.id==='a'?{data:bytes('one'),version:'v1'}:Promise.reject(new Error('download failed'))}));assert.deepEqual(await store.getArtifacts(),[]);const result=await syncPacket({store,tripId:'t',api:{packet:async()=>packet},fetchArtifact:async artifact=>({data:bytes(artifact.id==='a'?'one':'two'),version:'v1'})});assert.equal(result.trip.id,'t');assert.deepEqual((await store.getArtifacts()).map(item=>item.artifactId).sort(),['a','b']);});
test('checksum mismatch rejects candidate without committing it',async()=>{const artifact=await required('a','expected');const packet=await packetFor([artifact]);const store=new MemoryStore();await assert.rejects(syncPacket({store,tripId:'t',api:{packet:async()=>packet},fetchArtifact:async()=>({data:bytes('wrong'),version:'v1'})}),/checksum/);assert.equal(await store.getPacket('t'),null);});
test('readiness requires exact cached version/checksum and never treats dynamic access as offline-ready',async()=>{const a=await required('a','a'),b=await required('b','b'),c=await required('c','c');const packet=await packetFor([a,b,c]);const cached=artifact=>({id:artifactCacheId('t',artifact.eventId,artifact.id),tripId:'t',eventId:artifact.eventId,artifactId:artifact.id,state:'verified',version:artifact.version,checksum:artifact.checksum});assert.equal(readiness(packet,[cached(a),cached(b),cached(c)]).state,'ready_offline');assert.equal(readiness(packet,[cached(a),cached(b),{...cached(c),version:'old'}]).ready,2);assert.equal(readiness({...packet,access:[{status:'external_dynamic',artifactIds:['a']}]},[cached(a)]).ready,0);});
test('same artifact ID on another Event or Trip cannot satisfy readiness',async()=>{const ticket=await required('ticket','one');const packet={...await packetFor([ticket]),access:[{status:'expected',eventId:'e',artifactIds:['ticket']}]};const otherEvent={id:artifactCacheId('t','other','ticket'),tripId:'t',eventId:'other',artifactId:'ticket',state:'verified',version:'v1',checksum:ticket.checksum};const otherTrip={id:artifactCacheId('other-trip','e','ticket'),tripId:'other-trip',eventId:'e',artifactId:'ticket',state:'verified',version:'v1',checksum:ticket.checksum};assert.equal(readiness(packet,[otherEvent,otherTrip]).ready,0);const own={id:artifactCacheId('t','e','ticket'),tripId:'t',eventId:'e',artifactId:'ticket',state:'verified',version:'v1',checksum:ticket.checksum};assert.equal(readiness(packet,[otherEvent,otherTrip,own]).ready,1);});
test('offline queue survives a reload seam, replays successful mutations, and retains conflicts',async()=>{const store=new MemoryStore();await store.enqueue({id:'success',operation:'createKnowledge'});await store.enqueue({id:'conflict',operation:'updateEvent'});const reloaded=new MemoryStore({mutations:await store.pending()});const retained=await replayQueue(reloaded,{mutate:async mutation=>{if(mutation.id==='conflict'){const error=new Error('changed elsewhere');error.code='revision_conflict';throw error;}}});assert.equal(retained.length,1);assert.equal(retained[0].id,'conflict');assert.equal(retained[0].state,'conflict');assert.deepEqual(await reloaded.pending(),retained);});
test('client API request boundary requires bearer authentication and dispatches only whitelisted semantic mutations',async()=>{const calls=[];const service={createKnowledge:async(...args)=>{calls.push(args);return {id:'k'};}};const runtime=async token=>{assert.equal(token,'token');return {service,storage:{}};};await assert.rejects(handleClientMutation({body:{}},runtime),/Bearer token/);assert.deepEqual(await handleClientMutation({authorization:'Bearer token',body:{operation:'createKnowledge',arguments:{tripId:'t',knowledge:{title:'note',content:'x'}}}},runtime),{id:'k'});assert.deepEqual(calls,[['t',{title:'note',content:'x'}]]);await assert.rejects(dispatchClientMutation(service,{operation:'deleteEverything'}),/Unsupported/);});
