import test from 'node:test';
import assert from 'node:assert/strict';
import { PersistentPorterService } from '../src/persistent-service.js';
import { MemoryRepository } from './helpers/repository.js';
import { deleteAppEvent,eventDeletionPreview } from '../src/trip-deletion.js';
import { MemoryStore } from '../client/core.js';
import { withoutDeletedEvents } from '../client/deleted-events.js';
import { dispatchClientMutation } from '../client-api/server.mjs';
async function setup(){const repo=new MemoryRepository(),service=new PersistentPorterService(repo,'owner'),trip=await service.createTrip({title:'Keep Trip'}),parent=await service.createEvent(trip.id,{title:'Delete parent'}),child=await service.createEvent(trip.id,{title:'Delete child',parentEventId:parent.id}),other=await service.createEvent(trip.id,{title:'Keep Event'}),knowledge=await service.createKnowledge(trip.id,{title:'Keep note',content:'Useful',relatedEventIds:[child.id,other.id]});return {repo,service,trip,parent,child,other,knowledge};}
test('Event deletion removes only subtree and its metadata; retains Trip, siblings and Knowledge with revised links',async()=>{const x=await setup(),before=await x.service.getEvent(x.other.id),preview=await eventDeletionPreview(x.service,x.parent.id),result=await deleteAppEvent(x.service,x.parent.id,preview.expected);assert.deepEqual(new Set(result.eventIds),new Set([x.parent.id,x.child.id]));assert.deepEqual(await x.service.getEvent(x.other.id),before);assert.ok(await x.service.getTrip(x.trip.id));const k=await x.service.getKnowledge(x.knowledge.id);assert.deepEqual(k.relatedEventIds,[x.other.id]);assert.equal(k.revision,x.knowledge.revision+1);assert.equal((await x.service.listEvents(x.trip.id)).length,1);});
test('Event deletion rejects foreign owner, stale revisions, and generic conversational mutation',async()=>{const x=await setup(),preview=await eventDeletionPreview(x.service,x.child.id);await assert.rejects(deleteAppEvent(new PersistentPorterService(x.repo,'foreign'),x.child.id,preview.expected),/not found/);await x.service.updateEvent(x.child.id,{title:'Changed'},1);await assert.rejects(deleteAppEvent(x.service,x.child.id,preview.expected),/revision/i);assert.ok(await x.service.getEvent(x.child.id));await assert.rejects(dispatchClientMutation(x.service,{operation:'deleteEvent',arguments:{eventId:x.child.id}}),/Unsupported/);});
test('removed Events stay absent from cached perspectives, pending overlays and late packets',async()=>{const x=await setup(),packet=await x.service.tripContext(x.trip.id),store=new MemoryStore(),ids=[x.parent.id,x.child.id];await store.putPacket(x.trip.id,{packet,meta:{usable:true}});await store.putPacket(x.trip.id,{packet,meta:{usable:true}},'wes');await store.putArtifact({id:'pass',tripId:x.trip.id,eventId:x.child.id});await store.enqueue({operation:'updateEvent',arguments:{tripId:x.trip.id,eventId:x.child.id}});await store.removeEvents(x.trip.id,ids);await store.commitCandidate(x.trip.id,{packet,meta:{usable:true}},[]);for(const perspective of [null,'wes'])assert.deepEqual(Object.keys((await store.getPacket(x.trip.id,perspective)).packet.events),[x.other.id]);assert.equal((await store.pending()).length,0);assert.equal((await store.getArtifacts(x.trip.id)).length,0);assert.deepEqual(Object.keys(withoutDeletedEvents(packet,ids).events),[x.other.id]);});
