import test from 'node:test';
import assert from 'node:assert/strict';
import { newEvent } from '../src/domain.js';
import { activeJourney, doorEntries, eventTime, navigationFor, ticketSummary } from '../client/journey.js';
import { artifactCacheId, checksum } from '../client/core.js';

const bytes=value=>new TextEncoder().encode(value).buffer;
async function fixture(){const sum=await checksum(bytes('ticket'));const manifests=['wes','john','david'].map((participantId,index)=>({id:`ticket-${index}`,eventId:'opera',offlineRequired:true,version:'1',checksum:sum,mediaType:'image/png',code:{format:'qr',value:`pass-${index}`},satisfiesAdmissionIds:[`admission-${index}`]}));return {packetVersion:1,trip:{id:'trip',participants:[{id:'wes',name:'Wes'},{id:'john',name:'John'},{id:'david',name:'David'}]},events:{pastA:{id:'pastA',title:'Earlier',temporal:{end:'2026-01-01T10:00:00Z'}},pastB:{id:'pastB',title:'Latest past',temporal:{end:'2026-01-01T11:00:00Z'}},opera:{id:'opera',title:'Candide',temporal:{start:'2026-01-02T19:00:00+11:00',startTimezone:'Australia/Melbourne'},spatial:{location:{address:'Opera House'}},booking:{expectedAdmissions:[]}},move:{id:'move',title:'Flight',movement:true,temporal:{start:'2026-01-02T10:00:00+11:00',end:'2026-01-02T11:00:00+10:00',startTimezone:'Australia/Melbourne',endTimezone:'Australia/Brisbane'},spatial:{origin:{address:'MEL'},destination:{address:'BNE'}}}},current:{past:['pastA','pastB'],now:[],next:'opera',later:['move'],accommodation:[{eventId:'opera',location:{address:'Opera House'},knowledge:[]}],hire:[],parkingKnowledge:[]},knowledge:[],access:manifests.map((artifact,index)=>({eventId:'opera',participantId:['wes','john','david'][index],requirementId:`admission-${index}`,status:'expected',artifactIds:[artifact.id]})),artifactManifest:manifests};}

test('Active Journey consumes packet sections and keeps Past newest-first',async()=>{const packet=await fixture();const journey=activeJourney(packet);assert.equal(journey.current.accommodation.length,1);assert.deepEqual(journey.past.map(x=>x.title),['Latest past','Earlier']);assert.equal(journey.next.title,'Candide');assert.equal(journey.later[0].title,'Flight');});
test('movement navigation uses origin before departure and destination after departure',async()=>{const packet=await fixture(),move=packet.events.move;assert.match(navigationFor(move,'2026-01-01T00:00:00Z'),/MEL/);assert.match(navigationFor(move,'2026-01-02T01:00:00Z'),/BNE/);assert.equal(navigationFor({...move,spatial:{}},'2026-01-01T00:00:00Z'),null);});
test('Door Mode resolves all named admissions only from exact verified local artifacts',async()=>{const packet=await fixture();const good=await Promise.all(packet.artifactManifest.map(a=>({id:artifactCacheId('trip','opera',a.id),tripId:'trip',eventId:'opera',artifactId:a.id,state:'verified',version:'1',checksum:a.checksum,mediaType:a.mediaType,data:bytes(a.id)})));const entries=doorEntries(packet,'opera',good);assert.deepEqual(entries.map(x=>x.label),['Wes','John','David']);assert.ok(entries.every(x=>x.ready&&x.artifact.code));assert.equal(ticketSummary(packet,'opera',good),'3/3 ready offline');const incomplete=good.slice(0,2);assert.equal(ticketSummary(packet,'opera',incomplete),'2/3 ready offline');assert.equal(doorEntries(packet,'opera',[{...good[0],id:artifactCacheId('other','opera','ticket-0'),tripId:'other'}])[0].ready,false);});
test('dynamic tickets never claim offline readiness and local times retain supplied travel zones',async()=>{const packet=await fixture();packet.access[0].status='external_dynamic';const good=packet.artifactManifest.map(a=>({id:artifactCacheId('trip','opera',a.id),tripId:'trip',eventId:'opera',artifactId:a.id,state:'verified',version:'1',checksum:a.checksum}));assert.equal(ticketSummary(packet,'opera',good),'Requires venue app');const times=eventTime(packet.events.move);assert.notEqual(times.departure,times.arrival);});
test('artifact code metadata is validated as a subordinate artifact aspect',()=>{assert.doesNotThrow(()=>newEvent({title:'Ticket',artifacts:[{id:'a',role:'admission',mediaType:'image/png',version:'1',storageRef:{provider:'memory'},offlineRequired:true,code:{format:'qr',value:'abc'}}]},'trip'));assert.throws(()=>newEvent({title:'Ticket',artifacts:[{id:'a',role:'admission',mediaType:'image/png',version:'1',storageRef:{provider:'memory'},offlineRequired:true,code:{format:'unknown',value:'abc'}}]},'trip'),/Unsupported/);});
