import test from 'node:test';
import assert from 'node:assert/strict';
import { MemoryStore, packetCacheId, startLocalFirst } from '../client/core.js';
import { normalizeParticipants, participantRemovalAllowed } from '../client/library.js';

const packet=(id,perspectiveParticipantId=null)=>({packetVersion:1,revision:1,generatedAt:'2026-01-01T00:00:00Z',perspectiveParticipantId,trip:{id,title:`Trip ${id}`,lifecycle:id==='old'?'archived':'active',participants:[{id:'wes',name:'Wes'}]},events:{global:{id:'global',participants:[]}},current:{now:[],next:null,later:[]},artifactManifest:[],access:[]});
test('local Trip index retains active selection and archived packets without a second Trip truth model',async()=>{const store=new MemoryStore();await store.putPacket('old',{packet:packet('old'),meta:{usable:true,lastSync:'now'}});await store.setActiveTrip('old');assert.equal((await store.getActiveSelection()).tripId,'old');assert.equal((await store.listTripIndex())[0].lifecycle,'archived');assert.ok((await store.getPacket('old')).meta.usable);});
test('perspective packets have separate cache identities and an uncached perspective is not locally fabricated',async()=>{const store=new MemoryStore();await store.putPacket('trip',{packet:packet('trip'),meta:{usable:true}},null);await store.putPacket('trip',{packet:packet('trip','wes'),meta:{usable:true}},'wes');assert.notEqual(packetCacheId('trip',null),packetCacheId('trip','wes'));assert.equal((await store.getPacket('trip',null)).packet.perspectiveParticipantId,null);assert.equal((await store.getPacket('trip','wes')).packet.perspectiveParticipantId,'wes');assert.equal(await store.getPacket('trip','skye'),null);});
test('Trip switches render their own packet and deferred old-Trip work cannot replace the new Trip',async()=>{const store=new MemoryStore();await store.putPacket('a',{packet:packet('a'),meta:{usable:true}});await store.putPacket('b',{packet:packet('b'),meta:{usable:true}});const rendered=[];const run=await startLocalFirst({store,tripId:'b',api:{packet:async()=>packet('b'),artifact:async()=>null},render:async p=>rendered.push(p.trip.id)});await run.sync;assert.deepEqual(rendered,['b','b']);assert.notEqual((await store.getPacket('a')).packet.trip.id,(await store.getPacket('b')).packet.trip.id);});
test('participant IDs remain stable across display-name edits and referenced participants cannot be removed',()=>{const people=normalizeParticipants([{id:'wes',name:'Wesley'}]);assert.deepEqual(people,[{id:'wes',name:'Wesley'}]);assert.equal(participantRemovalAllowed({events:{e:{participants:['wes']}}},'wes'),false);assert.equal(participantRemovalAllowed({events:{e:{participants:['skye']}}},'wes'),true);});
test('pending mutations and conflicts remain scoped to their correct Trip',async()=>{const store=new MemoryStore();await store.enqueue({id:'a',operation:'updateEvent',arguments:{tripId:'a',eventId:'e'}});await store.enqueue({id:'b',operation:'updateEvent',state:'conflict',arguments:{tripId:'b',eventId:'e'}});const all=await store.pending();assert.equal(all.filter(m=>m.arguments.tripId==='a').length,1);assert.equal(all.filter(m=>m.arguments.tripId==='b'&&m.state==='conflict').length,1);});
