import test from 'node:test';
import assert from 'node:assert/strict';
import { calendarProjection, eventLocalDay, itineraryProjection, localDateTimeValue, planningDetails, withPendingEvents, zonedDateTimeToIso } from '../client/planning.js';
import { MemoryStore, replayQueue } from '../client/core.js';

const packet=()=>({packetVersion:1,trip:{id:'trip',title:'Planning trip',lifecycle:'upcoming',participants:[{id:'wes',name:'Wes'},{id:'skye',name:'Skye'}]},events:{
  parent:{id:'parent',title:'Cooking class',participants:[],temporal:{},spatial:{},commitment:'planned'},
  late:{id:'late',title:'Late Darwin',participants:['wes'],temporal:{start:'2026-03-01T14:45:00Z',end:'2026-03-01T15:45:00Z',startTimezone:'Australia/Darwin',endTimezone:'Australia/Darwin'},spatial:{location:{address:'Darwin'}},commitment:'confirmed'},
  tieB:{id:'tieB',title:'Bravo',participants:[],temporal:{start:'2026-03-02T00:00:00Z',startTimezone:'Australia/Darwin'},spatial:{},commitment:'optional'},
  tieA:{id:'tieA',title:'Alpha',participants:[],temporal:{start:'2026-03-02T00:00:00Z',startTimezone:'Australia/Darwin'},spatial:{},commitment:'cancelled'},
  child:{id:'child',title:'Market tour',parentEventId:'parent',participants:['skye'],temporal:{start:'2026-03-02T01:00:00Z',startTimezone:'Australia/Darwin'},spatial:{},commitment:'planned'},
  flight:{id:'flight',title:'Date line flight',movement:true,participants:[],temporal:{start:'2026-03-03T23:30:00Z',end:'2026-03-04T10:00:00Z',startTimezone:'Pacific/Honolulu',endTimezone:'Pacific/Auckland'},spatial:{origin:{address:'HNL'},destination:{address:'AKL'}},commitment:'planned'},
  sparse:{id:'sparse',title:'Find dinner',participants:[],temporal:{},spatial:{},commitment:'optional'}
},current:{past:[],now:[],next:null,later:[],accommodation:[],hire:[],parkingKnowledge:[]},knowledge:[{id:'k',title:'Room',content:'814',relatedEventIds:['late']}],access:[{eventId:'late',artifactIds:['ticket'],status:'expected'}],artifactManifest:[]});

test('itinerary groups by supplied local date, sorts deterministically, retains sparse Events, and does not duplicate composite parents',()=>{const plan=itineraryProjection(packet());assert.equal(eventLocalDay(packet().events.late),'2026-03-02');assert.equal(plan.days[0].day,'2026-03-02');assert.deepEqual(plan.days[0].events.map(x=>x.event.id),['late','tieA','tieB','child']);assert.equal(plan.days[0].events.at(-1).parent.id,'parent');assert.ok(!plan.days.flatMap(x=>x.events).some(x=>x.event.id==='parent'));assert.deepEqual(plan.unscheduled.map(x=>x.id),['sparse']);});
test('calendar uses local departure day, exposes overlap lanes, and excludes sparse Events',()=>{const source=packet();source.events.overlap={id:'overlap',title:'Overlap',participants:[],temporal:{start:'2026-03-01T14:50:00Z',end:'2026-03-01T16:00:00Z',startTimezone:'Australia/Darwin'},spatial:{},commitment:'planned'};const calendar=calendarProjection(source);const darwin=calendar.days.find(day=>day.day==='2026-03-02');assert.equal(darwin.blocks.find(block=>block.event.id==='late').lane,0);assert.equal(darwin.blocks.find(block=>block.event.id==='overlap').lane,1);assert.equal(calendar.days.find(day=>day.blocks.some(block=>block.event.id==='flight')).day,'2026-03-03');assert.ok(!calendar.days.flatMap(day=>day.blocks).some(block=>block.event.id==='sparse'));});
test('pending Event creation/edit overlays packet without mutating source and survives queue reload',async()=>{const source=packet(), mutation={id:'new-event',operation:'createEvent',arguments:{tripId:'trip',event:{title:'Pending coffee',temporal:{},spatial:{},participants:[],commitment:'planned'}}};const edit={id:'edit-event',operation:'updateEvent',arguments:{tripId:'trip',eventId:'late',patch:{title:'Edited Darwin',temporal:{start:'2026-03-02T15:00:00Z',startTimezone:'Australia/Darwin'}}}};const display=withPendingEvents(source,[mutation,edit]);assert.equal(display.events['pending:new-event'].pending,true);assert.equal(display.events.late.title,'Edited Darwin');assert.equal(source.events.late.title,'Late Darwin');assert.ok(itineraryProjection(display).unscheduled.some(event=>event.id==='pending:new-event'));const store=new MemoryStore({mutations:[mutation,edit]});const reloaded=new MemoryStore({mutations:await store.pending()});assert.equal(withPendingEvents(source,await reloaded.pending()).events['pending:new-event'].title,'Pending coffee');});
test('planning details promote related Knowledge and ticket/access information',()=>{const detail=planningDetails(packet(),'late');assert.equal(detail.knowledge[0].content,'814');assert.equal(detail.access[0].artifactIds[0],'ticket');});
test('Planning uses the already perspective-filtered packet and keeps missing Event aspects sparse',()=>{const source=packet();delete source.events.late;delete source.events.tieA;delete source.events.tieB;const plan=itineraryProjection(source);assert.ok(plan.days.flatMap(day=>day.events).every(row=>row.event.participants.includes('skye')||row.event.participants.length===0));const detail=planningDetails(source,'sparse');assert.equal(detail.event.spatial.location,undefined);assert.equal(detail.access.length,0);});
test('local editor values preserve Event timezones and convert changed local times in that zone',()=>{const value=localDateTimeValue('2026-03-01T14:45:00Z','Australia/Darwin');assert.equal(value,'2026-03-02T00:15');assert.equal(zonedDateTimeToIso(value,'Australia/Darwin'),'2026-03-01T14:45:00.000Z');assert.equal(eventLocalDay(packet().events.flight),'2026-03-03');});
test('revision conflicts remain queued for Planning resolution after replay',async()=>{const store=new MemoryStore({mutations:[{id:'conflict',operation:'updateEvent',arguments:{tripId:'trip',eventId:'late'}}]});const retained=await replayQueue(store,{mutate:async()=>{const error=new Error('changed');error.code='revision_conflict';throw error;}});assert.equal(retained[0].state,'conflict');assert.equal(withPendingEvents(packet(),retained).events.late.pendingConflict,true);});
test('authoritative packet cleanly replaces a replayed pending Event overlay',()=>{const source=packet(), mutation={id:'created',operation:'createEvent',arguments:{tripId:'trip',event:{title:'Pending',temporal:{},spatial:{},participants:[],commitment:'planned'}}};assert.ok(withPendingEvents(source,[mutation]).events['pending:created']);const authoritative=structuredClone(source);authoritative.events.server={id:'server',title:'Pending',temporal:{},spatial:{},participants:[],commitment:'planned'};const afterReplay=withPendingEvents(authoritative,[]);assert.equal(afterReplay.events['pending:created'],undefined);assert.equal(afterReplay.events.server.title,'Pending');});
