import test from 'node:test';
import assert from 'node:assert/strict';
import { PersistentPorterService } from '../src/persistent-service.js';
import { MemoryRepository } from './helpers/repository.js';
import { deleteAppTrip,tripDeletionPreview } from '../src/trip-deletion.js';
import { ConflictError } from '../src/domain.js';
import { MemoryStore,packetCacheId,startLocalFirst } from '../client/core.js';
import { createClientApi,dispatchClientMutation } from '../client-api/server.mjs';
import { AuthenticationError } from '../src/runtime.js';
import { createPorterMcpServer } from '../mcp/server.mjs';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
async function setup(){const removed=[],repo=new MemoryRepository(),storage={bucket:'porter-artifacts',delete:async ref=>removed.push(ref)},service=new PersistentPorterService(repo,'owner',storage),trip=await service.createTrip({title:'Delete me',participants:['wes']});const parent=await service.createEvent(trip.id,{title:'Day'}),child=await service.createEvent(trip.id,{title:'Meal',parentEventId:parent.id});await service.attachArtifactMetadata(child.id,{id:'pass',role:'ticket',version:'1',offlineRequired:false,mediaType:'text/plain',storageRef:{provider:'supabase-storage',bucket:storage.bucket,key:`${trip.id}/${child.id}/pass/original`}},child.revision);await service.createKnowledge(trip.id,{title:'Door',content:'Bring ID',relatedEventIds:[child.id],participantIds:['wes']});const other=await service.createTrip({title:'Keep me'});await service.createEvent(other.id,{title:'Kept'});await service.createKnowledge(other.id,{title:'Keep',content:'untouched'});return {repo,storage,removed,service,trip,other,child};}
test('app owner deletion removes aggregate/composite metadata, cleans only exact owned files, leaves other Trip intact',async()=>{const x=await setup(),before=await x.service.exportTrip(x.other.id,'json'),preview=await tripDeletionPreview(x.service,x.trip.id);const result=await deleteAppTrip(x.service,x.trip.id,preview.expected);assert.equal(result.deleted,true);assert.equal(result.cleanupPending,0);assert.equal(x.removed.length,1);assert.equal(x.repo.trips.has(x.trip.id),false);assert.equal((await x.repo.listEvents(x.trip.id)).length,0);assert.equal((await x.repo.listKnowledge(x.trip.id)).length,0);assert.ok([...x.repo.knowledge.values()].some(k=>k.title==='Door'&&k.tripId===null));assert.equal(await x.service.exportTrip(x.other.id,'json'),before);});
test('non-owner, missing revisions and stale Trip/Event/Knowledge revisions never delete',async()=>{for(const kind of ['trip','event','knowledge']){const x=await setup(),preview=await tripDeletionPreview(x.service,x.trip.id);await assert.rejects(deleteAppTrip(new PersistentPorterService(x.repo,'intruder'),x.trip.id,preview.expected),/not found/);await assert.rejects(deleteAppTrip(x.service,x.trip.id,null),TypeError);if(kind==='trip')await x.service.updateTrip(x.trip.id,{title:'Changed'},1);if(kind==='event')await x.service.createEvent(x.trip.id,{title:'Added after confirmation'});if(kind==='knowledge'){const k=(await x.service.listKnowledge(x.trip.id))[0];await x.service.updateKnowledge(k.id,{content:'New'},k.revision);}await assert.rejects(deleteAppTrip(x.service,x.trip.id,preview.expected),ConflictError);assert.ok(x.repo.trips.has(x.trip.id));assert.equal(x.removed.length,0);}});
test('storage cleanup is post-commit, failures are explicit, foreign and external references never removed',async()=>{const x=await setup();const child=x.repo.events.get(x.child.id);child.artifacts.push({id:'foreign',storageRef:{provider:'supabase-storage',bucket:'elsewhere',key:'other/file'}},{id:'external',storageRef:{provider:'external',url:'https://example.test/shared'}});x.storage.delete=async()=>{throw Error('storage down');};const logs=[],result=await deleteAppTrip(x.service,x.trip.id,(await tripDeletionPreview(x.service,x.trip.id)).expected,{logger:x=>logs.push(x)});assert.equal(result.cleanupPending,2);assert.equal(logs.length,1);assert.equal(x.repo.trips.has(x.trip.id),false);});
test('cache purge removes all perspectives, artifacts, pending edits and selection; delayed writes cannot resurrect',async()=>{const x=await setup(),packet=await x.service.tripContext(x.trip.id),store=new MemoryStore();await store.putPacket(x.trip.id,{packet,meta:{usable:true}},null);await store.putPacket(x.trip.id,{packet,meta:{usable:true}},'wes');await store.putArtifact({id:'ticket',tripId:x.trip.id});await store.enqueue({operation:'updateEvent',arguments:{tripId:x.trip.id}});await store.setActiveTrip(x.trip.id);await store.upsertTripIndex(x.other);await store.removeTrip(x.trip.id);await store.commitCandidate(x.trip.id,{packet,meta:{usable:true}},[{id:'late',tripId:x.trip.id}]);await store.upsertTripIndex(packet.trip);await store.putPacket(x.trip.id,{packet});assert.equal(await store.getPacket(x.trip.id,'wes'),null);assert.equal(store.packets.has(packetCacheId(x.trip.id)),false);assert.equal((await store.getArtifacts(x.trip.id)).length,0);assert.equal((await store.pending()).length,0);assert.equal(await store.getActiveTrip(),null);assert.deepEqual((await store.listTripIndex()).map(x=>x.id),[x.other.id]);let render=0;const run=await startLocalFirst({store,api:{},render:()=>render++});await run.sync;assert.equal(render,0);});
test('authenticated app DELETE is separate from generic mutations and MCP inventory',async t=>{const x=await setup(),app=createClientApi(async token=>{if(token!=='valid')throw new AuthenticationError();return {service:x.service};}),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>server.close());const url=`http://127.0.0.1:${server.address().port}/client/trips/${x.trip.id}`,headers={authorization:'Bearer valid','content-type':'application/json'};assert.equal((await fetch(url,{method:'DELETE',headers:{'content-type':'application/json'},body:'{}'})).status,401);const preview=await(await fetch(url+'/deletion',{headers})).json();await assert.rejects(dispatchClientMutation(x.service,{operation:'deleteTrip',arguments:{tripId:x.trip.id}}),/Unsupported/);assert.equal((await fetch(url,{method:'DELETE',headers,body:JSON.stringify({expected:preview.expected})})).status,200);assert.equal((await fetch(url+'/packet',{headers})).status,404);const mcp=createPorterMcpServer(x.service),client=new Client({name:'delete-boundary',version:'1'}),[a,b]=InMemoryTransport.createLinkedPair();await mcp.connect(a);await client.connect(b);try{assert.equal((await client.listTools()).tools.some(x=>/delete/i.test(x.name)),false);}finally{await client.close();await mcp.close();}});
