import { test,expect } from '@playwright/test';
test('MCP materialized original images sync, survive controlled restart and render all admissions locally in Door',async({page,request,context,browserName})=>{
 await page.addInitScript(()=>{const create=URL.createObjectURL.bind(URL);window.ticketBlobs=new Map();URL.createObjectURL=blob=>{const url=create(blob);window.ticketBlobs.set(url,blob);return url;};});
 await request.post('/__test/reset');const response=await request.post('/__test/ingest');expect(response.ok()).toBe(true);const data=await response.json();expect(data.artifacts).toHaveLength(3);expect(data.artifacts.every(a=>a.storageRef.provider==='supabase-storage')).toBe(true);
 await context.addCookies([{name:'browser-regression-access',value:'browser-regression',url:'http://localhost:4178',httpOnly:true,sameSite:'Strict'}]);await page.goto('/#'+data.tripId);await expect(page.locator('#status')).toHaveText('Sync complete');await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await expect(page.locator('#status')).toHaveText('Sync complete');await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);await expect(page.locator(`[data-tickets="${data.eventId}"]`)).toHaveText('3/3 ready offline');
 if(browserName==='chromium')await context.setOffline(true);else await request.post('/__test/connectivity',{data:{apiAvailable:false}});
 await page.reload();await expect(page.locator(`[data-tickets="${data.eventId}"]`)).toHaveText('3/3 ready offline');const artifactRequests=[];page.on('request',r=>{if(r.url().includes('/client/artifacts/'))artifactRequests.push(r.url());});await page.locator(`[data-tickets="${data.eventId}"]`).tap();
 for(let i=0;i<3;i++){const img=page.locator('#door #code img');await expect(img).toBeVisible();await expect(img).toHaveAttribute('src',/^blob:/);const hash=await img.evaluate(async e=>{const bytes=await window.ticketBlobs.get(e.src).arrayBuffer();return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');});expect(hash).toBe(data.hashes[i]);await expect.poll(()=>img.evaluate(e=>e.complete&&e.naturalWidth>0)).toBe(true);if(i<2)await page.locator('#door #next').tap();}expect(artifactRequests).toEqual([]);await page.locator('#door #close').tap();
});
