import { test,expect } from '@playwright/test';
let tripId,eventId;
test.beforeEach(async({page,context,request})=>{
 ({tripId,eventId}=await(await request.post('/__test/reset')).json());
 await context.addCookies([{name:'browser-regression-access',value:'browser-regression',url:'http://localhost:4178',httpOnly:true,sameSite:'Strict'}]);
 await page.goto(`/?porter-diagnostics=1#${tripId}`);await expect(page.locator('#status')).toHaveText('Sync complete');await page.evaluate(()=>navigator.serviceWorker.ready);
 await page.reload();await expect(page.locator('#status')).toHaveText('Sync complete');await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);
});
const serverEvent=async request=>(await(await request.get('/__test/events')).json()).find(e=>e.id===eventId);
async function diagnostic(page){
 const panel=page.locator('#porter-diagnostics');if(!await panel.evaluate(e=>e.open))await panel.locator('summary').tap();
 await panel.locator('[data-refresh]').tap();await expect(panel.locator('pre')).toContainText('mutations');return JSON.parse(await panel.locator('pre').innerText());
}
async function conflict(page,request){
 await request.post('/__test/mutation-hold');await page.locator(`[data-event="${eventId}"]`).first().tap();await page.locator('#details #edit').tap();
 await page.locator('[name=title]').fill('Unsynchronized local title');await page.locator('[data-save-event]').tap();await expect(page.locator('#details')).not.toBeVisible();
 await expect.poll(async()=>(await(await request.get('/__test/mutation-state')).json()).waiting).toBe(1);
 expect((await request.post('/__test/conflict-update')).ok()).toBe(true);await request.post('/__test/mutation-release');await expect(page.locator('[data-resolve-conflict]')).toBeVisible();
 await expect(page.locator(`[data-event="${eventId}"] strong`)).toHaveText('Unsynchronized local title');
}
test('stale edit survives controlled reload; safe diagnostics, cancelled discard and durable discard accept server',async({page,request})=>{
 await conflict(page,request);await page.reload();await expect(page.locator('[data-resolve-conflict]')).toBeVisible();
 const data=await diagnostic(page),m=data.mutations.find(m=>m.state==='conflict');expect(m).toMatchObject({operation:'updateEvent',tripId,eventId,expectedRevision:1,currentRevision:2,errorCode:'revision_conflict',projected:true});expect(m.id).toBeTruthy();expect(m.createdAt).toBeTruthy();expect(JSON.stringify(data.mutations)).not.toContain('Unsynchronized local title');expect(JSON.stringify(data.mutations)).not.toContain('Server-only');
 await page.locator('[data-resolve-conflict]').tap();await expect(page.locator('#details')).toContainText('Expected revision 1');await page.locator('[data-discard]').tap();await page.locator('[data-keep]').tap();await expect(page.locator('[data-confirm-discard]')).toHaveCount(0);await page.locator('#details #close').tap();expect((await diagnostic(page)).conflicts).toBe(1);
 await page.locator('[data-resolve-conflict]').tap();await page.locator('[data-discard]').tap();await page.locator('[data-confirm-discard]').tap();await expect(page.locator('#details')).not.toBeVisible();await expect(page.locator('[data-resolve-conflict]')).toHaveCount(0);await expect(page.locator(`[data-event="${eventId}"] strong`)).toHaveText('Authoritative server Event');await expect(page.locator('#status')).toHaveText('Sync complete');
 expect((await diagnostic(page)).conflicts).toBe(0);expect((await diagnostic(page)).pendingMutations).toBe(0);await page.reload();await expect(page.locator(`[data-event="${eventId}"] strong`)).toHaveText('Authoritative server Event');expect((await serverEvent(request)).revision).toBe(2);
});
test('unchanged retry never rebases; explicit current-state re-edit retains CAS and normal local Save',async({page,request})=>{
 await conflict(page,request);await page.locator('[data-resolve-conflict]').tap();await page.locator('[data-retry]').tap();await expect(page.locator('#details')).not.toBeVisible();await expect(page.locator('[data-resolve-conflict]')).toBeVisible();await expect.poll(async()=>(await diagnostic(page)).mutations[0].state).toBe('conflict');expect((await serverEvent(request)).revision).toBe(2);
 await page.locator('[data-resolve-conflict]').tap();await page.locator('[data-review]').tap();await expect(page.locator('[data-recovery-review]')).toContainText('Authoritative server Event');await page.locator('[data-confirm-discard]').tap();await expect(page.locator('[name=title]')).toHaveValue('Authoritative server Event');await expect(page.locator('[name=description]')).toHaveValue('Server-only information must survive recovery');
 await request.post('/__test/conflict-update',{data:{title:'Newer server edit'}});await page.locator('[name=title]').fill('Reviewed but now stale');await page.locator('[data-save-event]').tap();await expect(page.locator('#details')).not.toBeVisible();await expect(page.locator('[data-resolve-conflict]')).toBeVisible();expect((await serverEvent(request)).title).toBe('Newer server edit');
 await page.locator('[data-resolve-conflict]').tap();await page.locator('[data-review]').tap();await expect(page.locator('[data-recovery-review]')).toContainText('Newer server edit');await page.locator('[data-confirm-discard]').tap();await page.locator('[name=title]').fill('Deliberately reviewed Event');await page.locator('[data-save-event]').tap();await expect(page.locator('#details')).not.toBeVisible();await expect.poll(async()=>(await serverEvent(request)).title).toBe('Deliberately reviewed Event');await expect(page.locator('[data-resolve-conflict]')).toHaveCount(0);expect((await serverEvent(request)).description).toBe('Server-only information must survive recovery');expect((await serverEvent(request)).revision).toBe(4);
});
test('unrelated offline save synchronizes past conflict; offline discard removes overlay without network',async({page,request})=>{
 await conflict(page,request);await request.post('/__test/connectivity',{data:{apiAvailable:false}});await page.evaluate(()=>Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false}));
 await page.locator('#quick').tap();await page.locator('#quick-dialog #add-event').tap();await page.locator('[name=title]').fill('Independent offline Event');await page.locator('[data-save-event]').tap();await expect(page.locator('#quick-dialog')).not.toBeVisible();expect((await diagnostic(page)).pendingMutations).toBe(2);
 await request.post('/__test/connectivity',{data:{apiAvailable:true}});await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>true});window.dispatchEvent(new Event('online'));});await expect.poll(async()=>(await(await request.get('/__test/events')).json()).some(e=>e.title==='Independent offline Event')).toBe(true);await expect.poll(async()=>(await diagnostic(page)).pendingMutations).toBe(1);
 await request.post('/__test/connectivity',{data:{apiAvailable:false}});await page.evaluate(()=>Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false}));await page.locator('[data-resolve-conflict]').tap();await page.locator('[data-discard]').tap();await page.locator('[data-confirm-discard]').tap();await expect(page.locator('#details')).not.toBeVisible();await expect(page.locator('[data-resolve-conflict]')).toHaveCount(0);await expect(page.locator(`[data-event="${eventId}"] strong`)).toHaveText('Authoritative server Event');expect((await diagnostic(page)).pendingMutations).toBe(0);
});
test('discard explicitly names and atomically removes dependent local edits across IndexedDB ordering and reload',async({page,request})=>{
 await conflict(page,request);await page.locator(`[data-event="${eventId}"]`).first().tap();await page.locator('#details #edit').tap();await page.locator('[name=title]').fill('Dependent local title');await page.locator('[data-save-event]').tap();await expect(page.locator('#details')).not.toBeVisible();await expect.poll(async()=>(await diagnostic(page)).pendingMutations).toBe(2);
 await page.reload();await expect(page.locator('[data-resolve-conflict]')).toBeVisible();await page.locator('[data-resolve-conflict]').tap();await expect(page.locator('#details')).toContainText('1 later dependent edit');await page.locator('[data-discard]').tap();await expect(page.locator('[data-recovery-review]')).toContainText('1 dependent local edit');await page.locator('[data-confirm-discard]').tap();await expect(page.locator('#details')).not.toBeVisible();await expect(page.locator('[data-resolve-conflict]')).toHaveCount(0);await expect(page.locator(`[data-event="${eventId}"] strong`)).toHaveText('Authoritative server Event');expect((await diagnostic(page)).pendingMutations).toBe(0);await page.reload();await expect(page.locator(`[data-event="${eventId}"] strong`)).toHaveText('Authoritative server Event');expect((await serverEvent(request)).revision).toBe(2);
});
