import { test,expect } from '@playwright/test';
let tripId,otherId;
const state=async request=>(await(await request.get('/__test/aggregate')).json());
test.beforeEach(async({page,context,request})=>{await request.post('/__test/reset');({tripId,otherId}=await(await request.post('/__test/deletion')).json());await context.addCookies([{name:'browser-regression-access',value:'browser-regression',url:'http://localhost:4178',httpOnly:true,sameSite:'Strict'}]);await page.goto(`/#${tripId}`);await expect(page.locator('#status')).toHaveText('Sync complete');await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await expect(page.locator('#status')).toHaveText('Sync complete');});
async function edit(page){await page.locator('#library').tap();await expect(page.locator(`[data-trip-edit="${tripId}"]`)).toBeVisible();await page.locator(`[data-trip-edit="${tripId}"]`).tap();await page.locator('#delete-trip').tap();await expect(page.locator('#delete-confirmation')).toBeVisible();}
test('named confirmation cancel preserves aggregate; confirmed deletion purges cache and never returns after controlled reload',async({page,request})=>{
 const before=await state(request);await edit(page);await expect(page.locator('#delete-confirmation')).toContainText('Browser regression Trip');await expect(page.locator('#delete-confirmation')).toContainText('3 Events');await expect(page.locator('#delete-confirmation')).toContainText('cannot be undone');await page.locator('#cancel-delete').tap();expect(await state(request)).toEqual(before);await expect(page.locator('#trip-form')).toBeVisible();
 await page.locator('#delete-trip').tap();await expect(page.locator('#delete-confirmation')).toBeVisible();
 // Include another perspective and an unsent local draft in the same aggregate.
 await page.evaluate(async id=>{const db=await new Promise(resolve=>{const r=indexedDB.open('porter-v0',3);r.onsuccess=()=>resolve(r.result);});await new Promise(resolve=>{const tx=db.transaction(['packets','mutations'],'readwrite'),s=tx.objectStore('packets'),r=s.get(id+':perspective:everyone');r.onsuccess=()=>s.put({...r.result,id:id+':perspective:wes',perspectiveParticipantId:'wes'});tx.objectStore('mutations').put({id:'discarded-draft',operation:'createEvent',arguments:{tripId:id,event:{title:'Discard with Trip'}}});tx.oncomplete=resolve;});db.close();},tripId);
 await page.locator('#confirm-delete').tap();await expect(page.locator('#app h1')).toHaveText('Trips');await expect(page.locator(`[data-trip="${tripId}"]`)).toHaveCount(0);await expect(page.locator(`[data-trip="${otherId}"]`)).toBeVisible();const after=await state(request);for(const kind of ['trips','events','knowledge'])expect(after[kind]).toEqual(before[kind].filter(x=>kind==='trips'?x.id!==tripId:x.tripId!==tripId));
 const cache=await page.evaluate(async id=>{const db=await new Promise(resolve=>{const r=indexedDB.open('porter-v0',3);r.onsuccess=()=>resolve(r.result);});const rows={};for(const name of ['packets','artifacts','mutations','tripIndex','settings'])rows[name]=await new Promise(resolve=>{const r=db.transaction(name).objectStore(name).getAll();r.onsuccess=()=>resolve(r.result);});db.close();return Object.entries(rows).filter(([name])=>name!=='settings').flatMap(([name,values])=>values.filter(x=>x.tripId===id||x.id===id||x.arguments?.tripId===id));},tripId);expect(cache).toEqual([]);
 await page.reload();await expect(page.locator('#app h1')).toHaveText('Trips');await expect(page.locator(`[data-trip="${tripId}"]`)).toHaveCount(0);await page.goto(`/#${tripId}`);await expect(page.locator('#app h1')).toHaveText('Trips');await expect(page.locator(`[data-trip="${tripId}"]`)).toHaveCount(0);
});
test('failed backend deletion keeps local Trip and retry succeeds',async({page,request})=>{const before=await state(request);await edit(page);await request.post('/__test/delete-failure',{data:{fail:true}});await page.locator('#confirm-delete').tap();await expect(page.locator('#delete-message')).toContainText('Your local Trip is retained');expect(await state(request)).toEqual(before);await expect(page.locator('#library-dialog')).toBeVisible();await request.post('/__test/delete-failure',{data:{fail:false}});await page.locator('#confirm-delete').tap();await expect(page.locator('#app h1')).toHaveText('Trips');});
test('concurrent child creation after confirmation causes conflict and retains aggregate',async({page,request})=>{await edit(page);await request.post('/__test/deletion-change');const before=await state(request);await page.locator('#confirm-delete').tap();await expect(page.locator('#delete-message')).toContainText('Nothing was deleted');expect(await state(request)).toEqual(before);await page.locator('#cancel-delete').tap();await page.locator('#library-dialog #close').tap();await page.locator(`[data-trip="${tripId}"]`).tap();await expect(page.locator('.trip-overview h1')).toHaveText('Browser regression Trip');});
